version = 0 # DO NOT CHANGE

[minecraft]
host = '127.0.0.1' #default: 127.0.0.1
chat_method = 'management_server' #for getting messages from minecraft. Options: 'sftp'(not implemented)', 'management_server'(default)

[minecraft.management_server]
host = '0' #default: 0 (uses minecraft server ip)
port = 25585 #default: 25585
secret = ''

[minecraft.sftp]
host = '0' #default: 0 (uses minecraft server ip)
port = 22 #default: 22
username = 'minecraft' #default: minecraft
password = ''

[minecraft.rcon]
host = '0' #default: 0 (uses minecraft server ip)
port = 25575 #default: 25575
password = ''

[discord]
use_webhook = true #default: true
token = ''  #only required if use_webhook is false
channel_id = '' #required
webhook_url = '' #required if use_webhook is true 